Repository zendesk/zaf-toolbox, pull requests merged in 2025-09, with the labels that each got.

#222 chore: Implement Zaf Client type instead of relying on old package
  README.md
  __tests__/services/custom-fields-service.spec.ts
  __tests__/services/custom-objects.spec.ts
  __tests__/services/sunshine-conversation-api-service.spec.ts
  __tests__/services/zendesk-api-service.spec.ts
  __tests__/utils/create-custom-object.spec.ts
  __tests__/utils/get-from-client.spec.ts
  package-lock.json
  package.json
  src/models/zaf-client.ts
  src/services/custom-fields-service.ts
  src/services/custom-object-service.ts
  src/services/sunshine-conversation-api-service.ts
  src/services/zendesk-api-service.ts
  src/utils/create-custom-object.ts
  src/utils/get-from-client.ts
  src/utils/get-started-chat-event.ts
Labels: version: Major, size: L

#223 Add Create ticket endpoint to Zendesk API Client
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/models/zendesk-ticket.ts
  src/services/zendesk-api-service.ts
Labels: version: Minor, size: M

#224 chore: Implement Create many ticket endpoints
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/services/zendesk-api-service.ts
Labels: version: Minor, size: S

#229 chore: Implement get tickets endpoints
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/models/zendesk-ticket.ts
  src/services/zendesk-api-service.ts
Labels: version: Patch, size: S
