Repository zendesk/zaf-toolbox, pull requests merged in 2025-04, with the labels that each got.

#84 fix(sunshine-conversation-service): Response type for send notifications
  __tests__/services/sunshine-conversation-api-service.spec.ts
  package.json
  src/models/sunshine-conversation.ts
  src/services/sunshine-conversation-api-service.ts
Labels: bug, version: Patch, size: S

#90 chore(whats-app-template): update response type
  __tests__/services/sunshine-conversation-api-service.spec.ts
  package.json
  src/models/sunshine-conversation.ts
  src/models/whats-app-template.ts
  src/services/sunshine-conversation-api-service.ts
Labels: version: Patch, size: S

#102 feat(custom-object-service): Add search records method for Custom object service
  __tests__/services/custom-objects.spec.ts
  package.json
  src/models/custom-objects.ts
  src/services/custom-object-service.ts
Labels: version: Patch, size: M

#109 feat(zendesk user): Add custom user field type enum
  package.json
  src/models/zendesk-user.ts
Labels: version: Patch, size: S
