Repository zendesk/zaf-toolbox, pull requests merged in 2025-03, with the labels that each got.

#65 chore(typing): Add new type to WhatsApp template
  package.json
  src/models/whats-app-template.ts
Labels: version: Patch, size: S

#70 Update dependabot scheduled
  .github/dependabot.yaml
Labels: size: XS, dependabot

#71 Add new parameter_name type for WhatsApp templates
  package.json
  src/models/whats-app-template.ts
Labels: version: Patch, size: XS

#72 Add new type for WhatsApp templates headers
  package.json
  src/models/whats-app-template.ts
Labels: version: Patch, size: XS

#79 Implement SendNotification Response type
  __tests__/services/sunshine-conversation-api-service.spec.ts
  package.json
  src/models/sunshine-conversation.ts
  src/services/sunshine-conversation-api-service.ts
Labels: version: Patch, size: S
