Repository zendesk/zaf-toolbox, pull requests merged in 2025-01, with the labels that each got.

#8 chore(codeowner): Add Pol as codeowner of the repo
  .github/CODEOWNERS
Labels: version: Patch, size: XS

#19 Remove whatsapp namespace
  __tests__/utils/whats-app-helper.spec.ts
  package.json
  src/models/sunshine-conversation.ts
  src/utils/whats-app-helper.ts
Labels: version: Minor

#20 ci(release-workflow): Remove access restricted to npm publish command
  .github/workflows/release-workflow.yaml
  package.json
Labels: version: Patch, size: XS

#21 Downgrade version of ZendeskGarden Theming from 9.X to 8.76.9
  package-lock.json
  package.json
Labels: bug, version: Patch, size: XS

#22 Update our CIs
  .github/workflows/bump-version.yaml
  .github/workflows/main-workflow.yaml
  .github/workflows/release-workflow.yaml
Labels: bug
