Repository zendesk/zaf-toolbox, pull requests merged in 2025-07, with the labels that each got.

#176 Update `ICustomObjectRecordField` to not only accept string
  package.json
  src/models/custom-objects.ts
Labels: version: Patch, size: XS

#184 Filter is not saved when fetching records with different pages
  __tests__/services/custom-objects.spec.ts
  package.json
  src/services/custom-object-service.ts
Labels: version: Patch, size: S

#185 Include external_id in the body for Custom object records ( Body already include the key )
  __tests__/services/custom-objects.spec.ts
  package.json
  src/services/custom-object-service.ts
Labels: version: Patch, size: S

#186 Adding possibility to count elements without fetching all element for custom object filters
  __tests__/services/custom-objects.spec.ts
  package.json
  src/models/custom-objects.ts
  src/services/custom-object-service.ts
Labels: version: Minor, size: S

#197 Adding missing filed type for the custom object fields
  package.json
  src/models/custom-objects.ts
Labels: version: Patch, size: XS
