Repository zendesk/zaf-toolbox, pull requests merged in 2025-05, with the labels that each got.

#110 Add Zendesk user field options
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/models/zendesk-user.ts
Labels: version: Patch, size: S

#120 feat(zendesk-api-service): add function to fetch voice lines
  __tests__/services/sunshine-conversation-api-service.spec.ts
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/models/sunshine-conversation.ts
  src/models/zendesk-api.ts
  src/services/zendesk-api-service.ts
Labels: version: Minor, size: M

#121 chore(zendesk-api-service): update return type for voice lines
  package.json
  src/models/zendesk-api.ts
  src/services/zendesk-api-service.ts
Labels: version: Patch, size: S

#127 feat(zendesk-api-service): create function to get message history
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/models/zendesk-api.ts
  src/services/zendesk-api-service.ts
Labels: version: Minor, size: S

#128 chore(models): Update Iintegration for exporting Suncotwillio and talkTwillio
  package.json
  src/models/sunshine-conversation.ts
Labels: version: Patch, size: S

#140 feat(zendesk-api): add message status
  package.json
  src/models/zendesk-api.ts
Labels: version: Patch, size: XS

#137 feat: Add support for Zis Connection, Zis Token and zis webhook
  __tests__/services/zendesk-api-service.spec.ts
  package.json
  src/models/zendesk-api.ts
  src/models/zendesk-integration-services.ts
  src/services/zendesk-api-service.ts
Labels: version: Minor, size: M
